language: node_js
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get install -y iconv sed
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
script:
  - bash build_tools/travis_run_on.sh



