language: node_js
services:
  - docker
before_install:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
script:
  - bash build_tools/build_images.sh
deploy:
  - provider: script
    script: bash build_tools/push_images.sh
    on:
      branch: master

