language: node_js
services:
  - docker
before_install:
  - docker pull smokserwis/build:node10
script:
  - ng set --global warnings.packageDeprecation=false && \
  - mkdir -p /usr/lib/node_modules/angular-cli/node_modules/node-sass/vendor && \
  - npm install --unsafe-perm -g angular-cli && \
  - npm install -g @angular/cli
  - docker build --target backend -t Projekt-Napisany-W-Angular-8/backend:latest .
  - docker build --target frontend -t Projekt-Napisany-W-Angular-8/frontend:latest .
  - docker build Projekt-Napisany-W-Angular-8/mysql:latest mysql
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push smokserwis/Projekt-Napisany-W-Angular-8:frontend
  - docker push smokserwis/Projekt-Napisany-W-Angular-8:backend
  - docker push smokserwis/Projekt-Napisany-W-Angular-8:mysql


