version: '3.7'
services:
  mysql:
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    image: touzen666/projekt8:mysql
    networks:
     - projekt8
  backend:
    image: touzen666/projekt8:backend
    expose:
      - "80"
    links:
      - mysql
    networks:
      - projekt8
  frontend:
    image: touzen666/projekt8:frontend
    ports:
      - "80:80"
    environment:
      - HOSTNAME="localhost"
    links:
      - backend
    networks:
      - projekt8
      - bridge
volumes:
  mysql:
networks:
  projekt8:
    driver: bridge
    internal: true
  bridge:
    external:
      name: bridge

