version: '3.7'
services:
  mysql:
    volumes:
      - mysql:/var/lib/mysql
    hostname: mysql
    expose:
      - "3306"
    image: touzen666/projekt8:mysql
    networks:
      - backend
  backend:
    hostname: backend
    image: touzen666/projekt8:backend
    expose:
      - "8080"
    depends_on:
      - mysql
    environment:
      HOSTNAME="192.168.99.103"
    networks:
      - backend
  frontend:
    restart: "on-failure"
    image: touzen666/projekt8:frontend
    ports:
      - "80:80"
    environment:
      - HOSTNAME="localhost"
    depends_on:
      - backend
    networks:
      - backend
      - bridged
volumes:
  mysql:
networks:
  backend:
    driver: bridge
    internal: true
  bridged:
    internal: false
    driver: bridge
