version: '3.7'
services:
  mysql:
    image: mysql:5.7.9
    environment:
      - MYSQL_ROOT_PASSWORD=testpassword
      - MYSQL_DATABASE=outsourcing.pl
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    image: touzen666/projekt8:mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"
    hostname: mysql
    restart: "on-failure"
  backend:
    restart: "on-failure"
    image: touzen666/projekt8:backend
    hostname: backend
    depends_on:
      - mysql
    links:
      - mysql
    expose:
      - "8080"
  frontend:
    restart: "on-failure"
    image: touzen666/projekt8:frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    links:
      - backend
volumes:
  mysql:
