version: '3.7'
# To be run only development issues
services:
  mysql:
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    build:
      context: dockerfiles/mysql
      dockerfile: .
    networks:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    expose:
      - "80"
    links:
      - mysql
    networks:
      - backend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "80"
    links:
      - backend
  nginx:
    build:
      context: dockerfiles/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - backend
      - frontend
    environment:
      - HOSTNAME="192.168.100.99"
    networks:
      - backend
      - bridge
volumes:
  mysql:
networks:
  backend:
    internal: true
  bridge:
    internal: false

