version: '3.7'
services:
  mysql:
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    image: smokserwis/Projekt-Napisany-w-Angular-8:mysql
  backend:
    image: smokserwis/Projekt-Napisany-w-Angular-8:backend
    expose:
      - "80"
    links:
      - mysql
  frontend:
    image: smokserwis/Projekt-Napisany-w-Angular-8:frontend
    ports:
      - "80:80"
    links:
      - backend
volumes:
  mysql:
