version: '3.7'
services:
  mysql:
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    image: touzen666/projekt-napisany-w-angular-8/mysql
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
    networks:
     - projekt-napisany-w-angular-8
  backend:
    image: touzen666/projekt-napisany-w-angular-8/backend
    expose:
      - "80"
    links:
      - mysql
    deploy:
      mode: replicated
      endpoint_mode: dnsrr
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - projekt-napisany-w-angular-8
  frontend:
    image: touzen666/projekt-napisany-w-angular-8/frontend
    ports:
      - "80:80"
    deploy:
      mode: replicated
      endpoint_mode: dnsrr
      replicas: 2
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    networks:
       - projekt-napisany-w-angular-8
       - bridge
volumes:
  mysql:
networks:
  projekt-napisany-w-angular-8:
    driver: overlay
    internal: false
  bridge:
    external: true

