version: '3.7'
services:
  mysql:
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    image: touzen666/projekt8:mysql
    expose:
      - "3306"
    networks:
      - my-net
  backend:
    image: touzen666/projekt8:backend
    depends_on:
      - mysql
    links:
      - mysql
    expose:
      - "8080"
    networks:
      - my-net
  frontend:
    restart: "on-failure"
    image: touzen666/projekt8:frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    links:
      - backend
    networks:
      - my-net
volumes:
  mysql:
networks:
  my-net:
