version: '3.7'
services:
  mysql:
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    build:
      context: mysql
      dockerfile: Dockerfile
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    expose:
      - "80"
    links:
      - mysql
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "80:80"
    links:
      - backend
volumes:
  mysql:
